version: "3.8"
services:
    micro-service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "5001:5001"
        volumes:
            # setup file or folder public
            - micro-service:/app/public
        network_mode: bridge
        extra_hosts:
            - "host.docker.internal:host-gateway"
volumes:
    micro-service:
        external: false