info:
  title: Microservice API
  version: '1.0'
tags:
- name: Auth
- name: Todos
- name: Token
paths:
  /api/todo:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: &id001 {}
          description: Successful response
      tags: &id002
      - Todos
      summary: Add N List Todos
    post:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: *id001
          description: Successful response
      tags: *id002
      summary: Add N List Todos
  /api/todo/{id}:
    put:
      parameters:
      - &id003
        in: path
        name: id
        schema:
          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: &id004 {}
          description: Successful response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      tags: &id005
      - Todos
      summary: Edit N Delete Todos
    delete:
      parameters:
      - *id003
      responses:
        '200':
          content:
            application/json:
              schema: *id004
          description: Successful response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      tags: *id005
      summary: Edit N Delete Todos
  /api/auth/v1/login:
    post:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
      tags:
      - Auth
      summary: Login
  /api/auth/v1/register:
    post:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
      tags:
      - Auth
      summary: Register
  /api/token/validation:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
      tags:
      - Token
      summary: Self Process
  /api/todo/done/{id}/{is_done}:
    put:
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: is_done
        schema:
          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      tags:
      - Todos
      summary: Done Todos
  /api/token/validation-service:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
      tags:
      - Token
      summary: Microservice Process
openapi: 3.0.3
components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object

